source 'http://gems.github.com'    
source 'http://gems.rubyforge.org' 
source 'https://rubygems.org'   

ruby    '2.4.0' 
require 'rubygems'

platforms :ruby do
  gemspec :path => '.', :name => 'minimal-mistakes-jekyll', :group => :development, :require => true 
  gem "rake", ">= 12.0.0"
  gem "i18n", ">= 0.8.1"
  gem "minitest", ">= 5.10.1"
  gem "thread_safe", ">= 0.3.6"
  gem "builder", ">= 3.2.3"
  gem "erubis", ">= 2.7.0"
  gem "mini_portile2", ">= 2.1.0"
  gem "rack", ">= 1.6.5"
  gem "mime-types-data", ">= 3.2016.0521"
  gem "arel", ">= 6.0.4"
  gem "public_suffix", ">= 2.0.5"
  gem "bundler", ">= 1.14.6"
  gem "colorator", ">= 1.1.0"
  gem "concurrent-ruby", ">= 1.0.5"
  gem "diff-lcs", ">= 1.3"
  gem "multipart-post", ">= 2.0.0"
  gem "ffi", ">= 1.9.18"
  gem "forwardable-extended", ">= 2.6.0"
  gem "gemoji", ">= 3.0.0"
  gem "sass", ">= 3.4.23"
  gem "rb-fsevent", ">= 0.9.8"
  gem "kramdown", ">= 1.13.2"
  gem "liquid", ">= 3.0.6"
  gem "mercenary", ">= 0.3.6"
  gem "rouge", ">= 1.11.1"
  gem "safe_yaml", ">= 1.0.4"
  gem "jekyll-paginate", ">= 1.1.0"
  gem "thor", ">= 0.19.4"
  gem "rspec-support", ">= 3.5.0"
  gem "rvm", ">= 1.11.3.9"
  gem "tzinfo", ">= 1.2.2"
  gem "nokogiri", ">= 1.7.0.1"
  gem "rack-test", ">= 0.6.3"
  gem "mime-types", ">= 3.1"
  gem "addressable", ">= 2.5.0"
  gem "sprockets", ">= 3.7.1"
  gem "faraday", ">= 0.11.0"
  gem "rb-inotify", ">= 0.9.8"
  gem "pathutil", ">= 0.14.0"
  gem "jekyll-sass-converter", ">= 1.5.0"
  gem "rspec-core", ">= 3.5.4"
  gem "rspec-expectations", ">= 3.5.0"
  gem "rspec-mocks", ">= 3.5.0"
  gem "activesupport", ">= 4.2.8"
  gem "loofah", ">= 2.0.3"
  gem "mail", ">= 2.6.4"
  gem "sawyer", ">= 0.8.1"
  gem "listen", ">= 3.0.8"
  gem "rspec", ">= 3.5.0"
  gem "rails-deprecated_sanitizer", ">= 1.0.3"
  gem "globalid", ">= 0.3.7"
  gem "activemodel", ">= 4.2.8"
  gem "html-pipeline", ">= 2.5.0"
  gem "rails-html-sanitizer", ">= 1.0.3"
  gem "octokit", ">= 4.6.2"
  gem "jekyll-watch", ">= 1.5.0"
  gem "rails-dom-testing", ">= 1.0.8"
  gem "activejob", ">= 4.2.8"
  gem "activerecord", ">= 4.2.8"
  gem "jekyll-gist", ">= 1.4.0"
  gem "jekyll", ">= 3.4.2"
  gem "actionview", ">= 4.2.8"
  gem "jekyll-feed", ">= 0.9.1"
  gem "jekyll-redirect-from", ">= 0.12.1"
  gem "jekyll-sitemap", ">= 1.0.0"
  gem "jemoji", ">= 0.8.0"
  gem "actionpack", ">= 4.2.8"
  gem "actionmailer", ">= 4.2.8"
  gem "railties", ">= 4.2.8"
  gem "sprockets-rails", ">= 3.2.0"
  gem "rails", ">= 4.2.8"
end 